### ISSUE TITLE
License change without other participants.

### ISSUE THREAD

**Issue by krsshtx** [AidanHockey5/MegaBlaster2#10]
Hi Aidan!

Megablaster was open. People used to build and test it, report bugs, share ideas, code.
You used them. Now you call this engine "new" but it's definitely not.
No one was credited in the code.
You changed license, permit selling and started selling for yourself.

Everything ok?

**Comment by AidanHockey5** [comment]
Hello! 
I’m not sure what you mean? The engine was indeed built from scratch this time around. It took about 7 months of development time. Probably the only major carry-over is the track info screen, but even that was changed a bit. The file system was also painstakingly programmed from scratch this time around. 

I invite you to view the commit history of this project to see how it was developed over time. It’s all there.

Both the original MB and the MB2 were indeed solo projects, other than the libraries I utilized. My friend Natalie is probably the one I consulted with the most, and she gracefully offered one of her modified ring-buffer scripts as well as the constellation for analog stage. The latter of which she is literally credited on both sides of the board’s silk-screen front and back. That is who “Kunoichi” is.

The license is also exactly the same as the old MB. AGPL 3.0 for the code and CC-BY-NC-SA 4.0 for the hardware.  That is what I use for all of my projects. Users are more than welcome to create their own board for personal use, but I’m the only one permitted to sell them commercially, which I think is more than fair. This also allows contributions to the code-base should they ever arise.

I’m not entirely sure what your angle is with this issue, but I’m more than happy to answer any questions you may have.

**Comment by krsshtx** [comment]
Hi!
I mean exactly this thread where you gave up and then appeared again.
I would like you to answer.

https://github.com/AidanHockey5/STM32_VGM_Player_YM2612_SN76489/issues/2

**Comment by AidanHockey5** [comment]
Sure! At the time, I was convinced that I wouldn’t be able to solve that issue because I thought it was a hardware limitation rather than a software one.

The VGMEngine library I created was actually developed on the original MB before I began development on the MB2. I used the original MB as a prototyping platform, but the new engine worked so well that I decided to officially integrate it, even though the original MB was indeed end-of-life. I’m sorry that you seem to have been affected by this change in some way, but that’s progress. I even chose to integrate the new engine into my Throwback Operator OPL3 board too simply because I was so happy with how it turned out.

Also, keep in mind that posting code snippets in an issue isn’t exactly a contribution. You never submitted any pull-requests to contribute directly, therefore, I just considered your code as a separate fork that I wasn’t involved in. In-fact, nobody created any pull-requests for the original MB. Just to make things clear, your fork was not used as a reference in any way when developing my new engine, sorry.

**Comment by krsshtx** [comment]
> Just to make things clear, your fork was not used as a reference in any way when developing my new engine, sorry.

And you never looked inside, didn't try it on hardware and never though why it works better?

**Comment by AidanHockey5** [comment]
Sorry, can’t say that I did. Again, up until I made the new engine, I wasn’t planning on returning back to that project as there were a multitude of issues with the hardware as well (poorly routed, heavy analog interference, parts that are EOL, tiny RAM, etc.)
I apologize, but that’s the truth. For the MB2, I wanted a platform that was “done right,” so it was remade from scratch. The original MB is history to me at this point, but I figured I’d give those that bothered to create my project one last update since most of the work on it was already done.

**Comment by krsshtx** [comment]
Since there is no difference to me between old parseVGM function and your "new" class VGMEngineClass except  while(waitSamples <= 0) and no waits
I consider this as a marvellous transformation and can't believe you.
Sorry. There are no wonders.

**Comment by AidanHockey5** [comment]
...what are you even talking about? Did you even read the code? There are MASSIVE changes to how my old engine used to work.
https://github.com/AidanHockey5/MegaBlaster2/blob/master/lib/VGMEngine/VGMEngine.cpp

There is a completely new loader, buffer system, header parser, PCM loader, DAC stream processor, and state-machine. Of course the “waitSamples” line will look similar - it is literally part of the VGM specification to keep track of your wait samples before executing new commands.

Again, I still have no idea what your point is and this doesn’t seem to be an issue with the code, rather me personally for some reason. If you’d like to actually make a contribution, feel free to do so via a pull request, but if you’d like to continue to air your grievances towards me for what ever reason, I’d prefer if you’d just send me an email. https://www.aidanlawrence.com/contact/

**Comment by krsshtx** [comment]
>the “waitSamples” line will look similar - it is literally part of the VGM specification to keep track of your wait samples before executing new commands.

But without this little word the whole device is a garbage.

And you didn't make it right. And gave up.
Any loader you use.

**Comment by AidanHockey5** [comment]
Dude what lol

**Comment by krsshtx** [comment]
>Dude what lol

That's all happened after natarii talk was over.

**Comment by AidanHockey5** [comment]
This is probably the strangest “issue” I’ve ever seen haha
You seem to take issue with the fact that I learned something new and decided to integrate my new knowledge into an old project as a courtesy to those who decided to build the unit.

Feel free to do as you wish with your fork friend, but at this point, I’m not going to reply back to this thread. Again, sorry if you feel slighted in any way (...for some reason?) but I’m not interested in wasting more time on this. 

If this is how you behave, I am not interested in your contributions.

**Comment by krsshtx** [comment]
>If this is how you behave, I am not interested in your contributions.

I wrote here because you didn't reply in the other issue.
You don't answer emails.

You are too much in love with yourself.
It's a big delusion to think that I interested in contribution to a man who didn't mentioned anyone even in the code yet.
Very disappointed by you.

**Comment by AidanHockey5** [comment]
![9aa9521a43346b7749456bc93481c9d0](https://user-images.githubusercontent.com/9302383/111039676-18653480-83e4-11eb-8706-89dc8edfb252.gif)
